eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 18821203182
    url: jdbc:mysql://127.0.0.1/imooc?caracterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
     